Name
====

Task.Joose.NodeJS - Joose, packaged with NodeJS flavour.


SYNOPSIS
========

        require('Task/Joose/NodeJS')
        
        Class('Animal', {
            ...
        })

        
        Role('Winged', {
            has : {
                leftWing    : { is : 'rw' },
                rightWing   : { is : 'rw' }
            },
            
            methods : {
                
                flight : function () {
                    this.leftWing.flutter()
                    this.rightWing.flutter()
                },
                
                land : function () {
                    this.leftWing.hold()
                    this.rightWing.hold()
                }
            }
        })



        Class('Bird', {
            isa : Animal,
        
            does : Winged
        })


        Class('Gryphon', {
            isa : Lion,
            
            does : Winged
        })
        


DESCRIPTION
===========

`Task.Joose.NodeJS` is a distribution, containing Joose core bundled along with several essential extensions. Below is the composition:

> Joose                             [3.008](http://openjsan.org/doc/s/sa/samuraijack/Joose/3.008/lib/Joose.html)

>> Joose core, provides definitions for `Class/Role/Module` helpers

> JooseX.Attribute                  [0.02](http://openjsan.org/doc/s/sa/samuraijack/JooseX/Attribute/0.02/lib/JooseX/Attribute.html) 

>> Additional features for attributes

> JooseX.Namespace.Depended         [0.02](http://openjsan.org/doc/s/sa/samuraijack/JooseX/Namespace/Depended/0.02/lib/JooseX/Namespace/Depended.html)

>> Dependencies handling extension

> JooseX.CPS                        [0.02](http://openjsan.org/doc/s/sa/samuraijack/JooseX/CPS/0.02/lib/JooseX/CPS.html)

>> Trait, allowing to add the asynchronous (aka non-blocking) methods to your classes


Approach to modules 
===================

Joose was initially created to run in browser environment. Browser platform is less tolerant to synchronous resource loading than SSJS, as in older browsers it blocks the UI.
Thus, Joose wasn't able to adapt the CommonJS modules system (which is synchronous) and uses its own 

 

USAGE
=====

Scenario 1. Using Joose in Comm

To load Joose




GETTING HELP
============

This extension is supported via github issues tracker: <http://github.com/SamuraiJack/Task-Joose-NodeJS/issues>

For general Joose questions you can also visit #joose on irc.freenode.org or the forum at: <http://joose.it/forum>
 


SEE ALSO
========

Web page of this module: <http://github.com/SamuraiJack/Task-Joose-NodeJS/>

General documentation for Joose: <http://openjsan.org/go/?l=Joose>


BUGS
====

All complex software has bugs lurking in it, and this module is no exception.

Please report any bugs through the web interface at <http://github.com/SamuraiJack/Task-Joose-NodeJS/issues>



AUTHORS
=======

Nickolay Platonov <nplatonov@cpan.org>



COPYRIGHT AND LICENSE
=====================

Copyright (c) 2009, Nickolay Platonov

All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
* Neither the name of Nickolay Platonov nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission. 

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
